services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME}
      POSTGRES_PORT: ${POSTGRESQL_PORT}
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    env_file:
      - .env
